<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


// ganti 1
class Brg extends Model
{
    use HasFactory;

// ganti 2
    protected $table = 'nwmasbar';
    protected $primaryKey = 'NO_ID';
    public $timestamps = false;

// ganti 3
    protected $fillable = 
    [
        "SUB",
        "KDBAR",
        "NMBAR",
        "KET_UK",
        "KET_KEM",
        "HB",
        "HJ",
        "HET",
        "SUPP",
        "DT",
        "MARGIN",
        "ITEM_SUP",
        "TG_BELI1",
        "TG_BELI2",
        "QTY_BELI1",
        "TG_JUAL1",
        "TG_JUAL2",
        "QTY_JUAL1",
        "TG_ADA",
        "SA",
        "BL",
        "RB",
        "JL",
        "RJ",
        "KR1",
        "KR2",
        "BLRP",
        "RBRP",
        "JLRP",
        "RJRP",
        "KR1RP",
        "KR2RP",
        "SARP",
        "STM",
        "DIS_A",
        "DIS_B",
        "DIS_C",
        "LKB",
        "PPN",
        "TBL",
        "TJL",
        "TOT_JL",
        "TOT_BL",
        "TOT_RET",
        "TOT_JLRP",
        "TOT_BLRP",
        "TOT_RETRP",
        "ORDER_L",
        "QB1",
        "TQB1",
        "BARCODE",
        "CAT",
        "TGL_CAT",
        "JL_LL",
        "JL_LL2",
        "JL_LL3",
        "RJ_LL",
        "RJ_LL2",
        "RJ_LL3",
        "JLRP_LL",
        "JLRP_LL2",
        "JLRP_LL3",
        "RJRP_LL",
        "RJRP_LL2",
        "RJRP_LL3",
        "HADIAH_1",
        "HADIAH_2",
        "TGH",
        "NETRP",
        "JLNET_LL",
        "JLNET_LL2",
        "JLNET_LL3",
        "TGL_MULAI",
        "TGL_AKHIR",
        "DIS_SUP",
        "BEBAN",
        "TGL_MULAI2",
        "TGL_AKHIR2",
        "DIS_SUP2",
        "BEBAN2",
        "BASIC",
        "LAKU",
        "BKHENDRI",
        "TD_OD",
        "ALASAN",
        "TG_TD_OD",
        "HJ_LL",
        "TGUU3",
        "KET",
        "DT_BRG",
        "TG_DT_BRG",
        "ITEM_BRG",
        "RAK",
        "HB_AKIR",
        "PP",
        "T_BAR",
        "SUB_KE2",
        "RETUR",
        "BKNOL",
        "TGNOL",
        "KD_EVENT",
        "STO",
        "EDISI",
        "FAKTUR",
        "TG_FAKTUR",
        "TG_PJL",
        "A1",
        "SUPP2",
        "NO_PJL",
        "PMSR_PROD",
        "HB_FR",
        "DISC",
        "HJ_DISC",
        "RAK2"
    ];
}
