<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


// ganti 1
class Sup extends Model
{
    use HasFactory;

// ganti 2
    protected $table = 'nwmassup';
    protected $primaryKey = 'NO_ID';
    public $timestamps = false;

// ganti 3
    protected $fillable = 
    [
        "NO_SUPL",
        "NAMA",
        "ALMT_K",
        "KOTA",
        "ALMT_GD",
        "TLP_K",
        "NO_FAX",
        "NO_TELEX",
        "PEMILIK",
        "ALMT_R",
        "TLP_R",
        "NO_REK",
        "NAMA_B",
        "KOTA_B",
        "AN_B",
        "GOL_BRG",
        "JEN_BRG1",
        "JEN_BRG2",
        "STM_PEMBL",
        "KD_PEMBY",
        "CARA",
        "DISC_PS",
        "BG_PERS",
        "LAIN1",
        "LAIN2",
        "ORDER",
        "STATUSNYA",
        "GOLONGAN",
        "KOD_MIN",
        "JAM",
        "T_EN",
        "J_EN",
        "BUDGET",
        "KLB2",
        "LABEL",
        "DIS_A",
        "DIS_B",
        "DIS_C",
        "SA",
        "AM",
        "BY",
        "TR",
        "BEBAN",
        "ACC",
        "TARGET",
        "FLAG",
        "L_COUNTER",
        "J_COUNTER",
        "NON_DATA",
        "HAPUS",
        "TGL_HAPUS",
        "KET_HAPUS",
        "FLAG_BM1",
        "FLAG_BM2",
        "FLAG_BM3",
        "NO_TEGUR",
        "P_BM1",
        "P_BM2",
        "P_BM3",
        "FLAG_SB1",
        "FLAG_SB2",
        "FLAG_SB3",
        "NO_TEGUR2",
        "P_SB1",
        "P_SB2",
        "P_SB3",
        "CETAK_MIN",
        "CET_TEGUR",
        "PPN",
        "BUDGET_LL",
        "BUDGET_AWL",
        "NO_SP_P",
        "NO_SP_R",
        "NO_SP_T",
        "MATERAI",
        "AKT_ACC",
        "CAT",
        "CAT2",
        "CAT3",
        "SUP_BARU",
        "ZONA",
        "CAT_SP",
        "TGL_PS",
        "TGTERBIT",
        "TG_REAL",
        "DIS_P4",
        "KONSY",
        "CAT4",
        "TAHAN",
        "SUB_KE2",
        "FAC_SIDL",
        "NM_NPWP",
        "NO_NPWP",
        "AL_NPWP",
        "TG_NPWP",
        "RETUR",
        "TJ_EVEN",
        "TJ_MULAI",
        "TJ_AKHIR",
        "EMAIL",
        "CABANG_B",
        "SUB",
        "TGL_RUBAH",
        "JAM_RUBAH",
        "PMSR_PROD",
        "VA_TD",
        "ANB_VA_TD",
        "DEPT"
    ];
}
